version: '3.1'
services:
  signal1:
    build:
      context: CryptoP2P.Backend
      dockerfile: Dockerfile
    ports:
      - 8080:80
  signal2:
    build:
      context: CryptoP2P.Backend
      dockerfile: Dockerfile
    ports:
      - 8081:80
  app:
    build:
      context: CryptoP2P
      dockerfile: Dockerfile
    ports:
      - 80:80